

# This file was *autogenerated* from the file init.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3)
p = _sage_const_7 

R = QQ['x, y, z']; (x, y, z,) = R._first_ngens(3)
weight = [_sage_const_1 ,_sage_const_3 ,_sage_const_1 ]

