# SageMath: decompose a representation from traces given on a user-specified element order
# Works for an arbitrary permList (0-based one-line notation) and traceList
# Assumes permList lists *all* elements of the group in the order you want.

def decompose_from_permlist_traces(permList, traceList, verbose=True):
    """
    permList : list of permutations in 0-based one-line notation.
               Each perm is a list p of length n with entries 0..n-1, meaning i -> p[i].
               This list is assumed to be the full set of group elements (in your chosen order).
    traceList: list of traces chi(g) in exactly the same order as permList.

    Returns:
      (G, elems, decomposition)
      where decomposition is a list of dicts: {'index','degree','mult','irrep'}
    """
    if not permList:
        raise ValueError("permList is empty")
    n = len(permList[0])
    if any(len(p) != n for p in permList):
        raise ValueError("All permutations in permList must have the same length")
    if len(traceList) != len(permList):
        raise ValueError(f"Need {len(permList)} traces; got {len(traceList)}")

    # Validate each permutation is a bijection of 0..n-1
    target = list(range(n))
    for p in permList:
        if sorted(p) != target:
            raise ValueError(f"Not a permutation of 0..{n-1}: {p}")

    Sn = SymmetricGroup(n)

    def Sn_from_zero_based_oneline(p0):
        # Convert 0-based images to Sage's 1-based images for SymmetricGroup(n)
        return Sn([x + 1 for x in p0])

    # Elements in EXACTLY your order
    elems = [Sn_from_zero_based_oneline(p) for p in permList]

    # Build group generated by these elements
    G = PermutationGroup(elems)

    if verbose:
        print(f"n = {n}")
        print("Group order (generated by permList):", G.order())
        print("permList length:", len(permList))
        print("elems[0] is identity?", elems[0] == G.identity())
        if G.order() != len(permList):
            print("WARNING: permList length != group order.")
            print("         If permList is intended to list ALL elements, something is off:")
            print("         - permList may not be closed under multiplication, or")
            print("         - permList may omit elements, or")
            print("         - permList includes elements not in the generated group (unlikely).")

    # Decompose using inner products with irreducible characters
    irr = G.irreducible_characters()
    order = ZZ(G.order())

    decomposition = []
    for i, psi in enumerate(irr):
        s = sum(traceList[j] * psi(elems[j]).conjugate() for j in range(len(elems)))
        mult = s / order
        try:
            multZ = ZZ(mult)
        except Exception:
            multZ = mult
        decomposition.append({
            "index": i,
            "degree": psi.degree(),
            "mult": multZ,
            "irrep": psi
        })

    if verbose:
        print("\nNonzero irreducible multiplicities:")
        for d in decomposition:
            if d["mult"] != 0:
                print(f"  irrep #{d['index']}: mult={d['mult']}, degree={d['degree']}")
        dim = sum(d["mult"] * d["degree"] for d in decomposition)
        print("\nDimension check:")
        print("  sum(mult*degree) =", dim)
        print("  trace at identity (traceList[0]) =", traceList[0])

    return G, elems, decomposition


# ----------------- Example (your D5 data) -----------------
# permList = [
#     [0,1,2,3,4],
#     [1,2,3,4,0],
#     [2,3,4,0,1],
#     [3,4,0,1,2],
#     [4,0,1,2,3],
#     [0,4,3,2,1],
#     [1,0,4,3,2],
#     [2,1,0,4,3],
#     [3,2,1,0,4],
#     [4,3,2,1,0],
# ]
permList =[[1,2,0,3,4,5,6,7,8,9],#  -- cycle (0 1 2)
[0,2,3,1,4,5,6,7,8,9],#  -- cycle (1 2 3)
[3,1,2,0,4,5,6,7,8,9]]; 
# traceList = [20,0,0,0,0,-4,-4,-4,-4,-4]
traceList = [5571837825314881842744850576903774559419789222158729797286479239809493665069231584517931117580222502537701453485933121/444711415923733718710471013155402990631480822647000909120178242796770359743970191841936650069609017311683729962246274, 13,7114361204738425017886802966169981190926054490077647234216682765053563099120814593168407670995373462950981480431528573/444711415923733718710471013155402990631480822647000909120178242796770359743970191841936650069609017311683729962246274]

G, elems, dec = decompose_from_permlist_traces(permList, traceList, verbose=True)
