

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_9 = Integer(9)
import subprocess

# a = subprocess.run(["M2", "--script", "test.m2", "81","a9"],capture_output=True).stdout
# os.system("M2 --script test.m2 8")
# print((str(a)))

def run_macualay2_program(file_name, args):
	ls = ["M2", "--script", file_name]
	for arg in args:
		ls.append(str(arg))
	a = subprocess.run(ls,capture_output=True).stdout
	return a

a = run_macualay2_program("test.m2", [_sage_const_9 ])

print(str(a))

